---
clone:
  depth: 1
kind: pipeline
name: buster 386 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh buster debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh buster debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh buster debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh buster debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: buster armv7 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh buster debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh buster debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh buster debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh buster debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: buster amd64 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh buster debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh buster debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh buster debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh buster debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: buster arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh buster debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh buster debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh buster debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh buster debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- buster 386 build
- buster armv7 build
- buster amd64 build
- buster arm64 build
kind: pipeline
name: buster index
platform:
  os: linux
pull: always
steps:
- commands:
  - /usr/local/bin/index zerotier-builds debian buster 386 armv7 amd64 arm64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: index build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - /usr/local/bin/index zerotier-releases debian buster 386 armv7 amd64 arm64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: index release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- buster index
kind: pipeline
name: buster 386 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh buster debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh buster debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- buster index
kind: pipeline
name: buster armv7 test
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh buster debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh buster debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- buster index
kind: pipeline
name: buster amd64 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh buster debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh buster debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- buster index
kind: pipeline
name: buster arm64 test
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh buster debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh buster debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
kind: signature
hmac: b5682c0bf86250616c7ae236c7a78f3b7d8012635e36db093cb71f7fe590a38e

...
